#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
GUI="$HERE/usr/bin/NetBuddies.Server.Gui"
SERVER="$HERE/usr/bin/NetBuddies.Server"

if [ -x "$GUI" ] && [ "$NETBUDDIES_SERVER_CLI" != "1" ]; then
    exec "$GUI" "$@"
fi

exec "$SERVER" "$@"
